### ISSUE TITLE
Unable to use in combination with table modifying behaviors

### ISSUE THREAD

**Issue by trurl-master** [AthensFramework/PropelJS#5]
Currently, it seems impossible to use other behaviors that change table structure, like for example Propel Timestampable. modifyDatabase in PropelJSBehavior is called before all modifyTable methods in other behaviors thus making all those changes invisible for PropelJS.

The solution I use is to move the main piece to modifyTable, but execute it after all tables are processed.

**Comment by JASchilz** [comment]
Labeled as bug. I'm open to a pull request! Our shop is no longer using this package, so I would probably be slow to fix it myself. But I've put enough work into it that I'd like to see bugs fixed eventually.

**Comment by trurl-master** [comment]
tbh, I didn't test it extensively so I'm not sure it'll work for all cases.
I also guess that it will allow using propel default behavior ordering mechanism.

**Comment by JASchilz** [comment]
Acknowledged. I'll check it out at work this week!

**Comment by JASchilz** [comment]
Resolved by #6. Releasing as 1.0.0.
